services:
  _defaults:
    autowire: true
    public: false

  Ivoz\Core\Infrastructure\Domain\Service\Gearman\Manager:
    tags:
      - { name: test_double, fake: 'Ivoz\Core\Infrastructure\Domain\Service\Gearman\FakeManager' }

  Ivoz\Core\Infrastructure\Domain\Service\Gearman\FakeManager: ~

  ###############################################
  ## Jobs
  ###############################################

  Ivoz\Core\Infrastructure\Domain\Service\Gearman\Jobs\Xmlrpc:
    shared: false
    arguments:
      $manager: '@Ivoz\Core\Infrastructure\Domain\Service\Gearman\Manager'
      $settings: '%gearmand%'
